In [1]:
import numpy as np

In [4]:
#Numpy기반 데이터 타입은 ndarray
#array() : 리스트와 같은 다양한 인자를 입력 받아서 ndarray로 변환
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1)) 
print('array1 array 형태:', array1.shape) #.shape: ndarray의 차원과 크기를 튜플형태로 나타내줌 

array2 = np.array([[1,2,3], [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape) #2차원 array, 2개의 로우와 3개의 컬럼 => 2*3 = 6개의 데이터

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape) #2차원 array, 1개의 로우와 3개의 컬럼

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [7]:
#ndarray의 데이터 타입
#한개의 ndarray 객체에 int와 float가 함께 있을 수 없음
#.dtype : ndarray내의 데이터 타입 확인
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [8]:
#만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 coercion
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) #1, 2를 모두 string으로 coercion 
 
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # 1, 2를 모두 float으로 coercion

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [11]:
#astype(): ndarray 내 데이터값의 타입 변경
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_int.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32') #float -> int : 소수점 이하 사라짐
print(array_int2, array_int2.dtype)

[1. 2. 3.] int32
[1 2 3] int32
[1 2 3] int32


In [13]:
#ndarray를 편리하게 생성하기 - arange, zeros, ones : 연속값이나 0 또는 1로 초기화해 쉽게 생성할때
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [14]:
zero_array = np.zeros((3,2), dtype='int32') #모든 값을 0으로
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape) #모든 값을 1로

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [17]:
#ndarray의 차원과 크기를 변경 : reshape()
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5) #2로우 * 5컬럼
print('array2:\n', array2)

array3 = array1.reshape(5, 2) #5로우 * 2컬럼
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [22]:
#reshape()에 -1을 인자로 하면 호환되는 새로운 shape 반환
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
print(array2)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [28]:
#reshape(-1, 1)와 같은 형태로 자주 사용
#why? ndarray가 어떤 형태라도 2차원 & 여러개의 로우를 가지되 반드시 1개의 컬럼
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [29]:
#Numpy의 ndarray의 데이터 세트 선택하기 - Indexing
#이건 아는 내용이니까 넘긴다

In [33]:
#행렬의 정렬 - sort() & argsort()
#행렬 정렬 - np.sort(), ndarray.sort()
#np.sort() : 원 행렬은 그대로 유지한 채 정렬된 행렬 반환 / ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환, 반환값은 None
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [34]:
#sort()를 내림차순으로 정리하기
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [37]:
#행렬이 2차원 이상일 경우 => axis축 값 설정을 통해 로우 방향(axis = 0) or 컬럼 방향(axis = 1)으로 정렬을 수행
array2d = np.array([[8, 12],
                    [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [38]:
#np.argsort() : 정렬 행렬의 원본 행렬 인덱드를 ndarray형으로 반환
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [40]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [41]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc]) #팬시 인덱스를 적용해 추출

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [43]:
#선형대수 연산 - 행렬 내적과 전치 행렬 구하기 
#행렬 내적(행렬 곱) - np.dot()
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [44]:
#전치 행렬 - np.transpose()
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
